default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: api_sms_development
  username: root
  host: db
  password:

test:
  <<: *default
  database: api_sms_test
  username: root
  host: db

production:
  <<: *default
  database: api_sms
  username: root
  host: db
